DROP TABLE IF EXISTS API_VUELOS;

CREATE TABLE API_VUELOS (
  ID BIGINT AUTO_INCREMENT,
  FECHA_SALIDA DATE,
  FECHA_LLEGADA DATE,
  CIUDAD_ORIGEN VARCHAR,
  CIUDAD_DESTINO VARCHAR,
  NOMBRE_PASAJERO VARCHAR,
  EDAD_PASAJERO INT,
  TIENE_BODEGA_EQUIPAJE BIT,
  PRECIO DECIMAL,
  HORA_SALIDA TIME,
  HORA_LLEGADA TIME
);
